services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "4000:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  order-worker:
    build:
      context: ./order-worker
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./order-worker:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_mart
    ports:
      - "5433:5432"
    volumes:
      - emart_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@emart.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  emart_pgdata:
